remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme 
title: q2-makarsa
description: A QIIME 2 plug-in to expose some functionality from the SpiecEasi and FlashWeave packages together with additional network visualisation.
show_downloads: true
github:
  repository_url: https://github.com/BenKaehler/q2-makarsa
  tar_url: https://github.com/BenKaehler/q2-makarsa/tarball/main
  zip_url: https://github.com/BenKaehler/q2-makarsa/zipball/main
  owner_url: https://github.com/BenKaehler/
  owner_name: Ben Kaehler
