remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme 
title: [q2-makarsa]
description: [A QIIME 2 plug-in to expose some functionality from the SpiecEasi and FlashWeave packages together with additional network visualisation.]
show_downloads: [true]
